from typing import Protocol

from edceleste.services.models.settings_model import SettingsIssueModel, SettingsModel


class SttProtocol(Protocol):
    def validate_settings(
        self, new_settings: SettingsModel
    ) -> SettingsIssueModel | None: ...

    def reload_service(self) -> None: ...

    def is_stt_enabled(self) -> bool: ...

    def get_stt_models(self) -> list[str]: ...

    def get_stt_input_devices(self) -> list[tuple[str, int]]: ...

    def start_recording(self) -> None: ...

    def stop_recording(self) -> str | None: ...
