from collections.abc import AsyncGenerator
from typing import Protocol

from services.models.llm_response import LLMResponse, LLMStatus
from services.models.settings_model import SettingsIssueModel, SettingsModel


class LLMProtocol(Protocol):
    def get_llm_healthcheck(self) -> bool: ...
    async def send_message(self, message: str) -> None: ...
    def stream_responses(self) -> AsyncGenerator[LLMResponse, None]: ...
    def stream_llm_status(self) -> AsyncGenerator[LLMStatus, None]: ...
    def validate_settings(
        self, new_settings: SettingsModel
    ) -> SettingsIssueModel | None: ...
    def reload_service(self) -> None: ...
